redstone:
  enabled: true

dimensions:
  enabled: true
  nether:
    enabled: true
    world: world_nether
  end:
    enabled: true
    world: world_the_end

behavior-packs:
  enabled: true
  folder: behavior_packs
  items-and-blocks: true
  entities: true
  recipes: true
  loot-tables: true
  scripts: true
  script-timeout-ms: 2000

dummies:
  enabled: true
