<?php

declare(strict_types=1);

namespace VanillaAltay\command;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\math\Vector3;
use pocketmine\permission\DefaultPermissionNames;
use pocketmine\player\Player;
use pocketmine\utils\Random;
use pocketmine\utils\TextFormat;
use pocketmine\world\format\Chunk;
use pocketmine\world\World;
use VanillaAltay\world\generator\biome\VanillaBiomeSelector;
use VanillaAltay\world\generator\noise\NoiseRouter;
use VanillaAltay\world\generator\overworld\VanillaOverworld;
use VanillaAltay\world\generator\structure\Structure;
use VanillaAltay\world\generator\structure\StructurePlacement;
use VanillaAltay\world\generator\structure\StructureRegistry;
use function array_keys;
use function ceil;
use function count;
use function implode;
use function is_numeric;
use function max;
use function min;
use function round;
use function sort;
use function sqrt;
use function str_replace;
use function strtolower;
use function ucfirst;

/**
 * The vanilla command, limited to the biome mode: locating structures needs structures to exist first.
 *
 * Vanilla can answer instantly because the server owns the biome source. Here the generator runs on worker
 * threads, so the command rebuilds the same selector from the world seed and walks a square spiral outwards
 * one chunk at a time, exactly like a biome search does when the chunks aren't generated yet.
 */
final class LocateCommand extends Command{

	private const DEFAULT_RADIUS_CHUNKS = 96;
	private const MAX_RADIUS_CHUNKS = 256;

	/**
	 * Hard ceiling on the work one search may do, so a command can never hang the server: the spiral walks a
	 * square, and its area grows fast enough that a large radius alone would freeze it for minutes.
	 */
	private const MAX_SAMPLES = 40000;

	public function __construct(){
		parent::__construct("locate", "Locates the closest biome or structure of the given kind", "/locate <biome|structure> <name> [radius] [teleport]");
		$this->setPermission(DefaultPermissionNames::GROUP_OPERATOR);
	}

	public function execute(CommandSender $sender, string $commandLabel, array $args) : bool{
		if(!$this->testPermission($sender)){
			return true;
		}

		if(!$sender instanceof Player){
			$sender->sendMessage(TextFormat::RED . "This command can only be used in game");
			return true;
		}

		$mode = strtolower($args[0] ?? "");
		if(count($args) < 2 || ($mode !== "biome" && $mode !== "structure")){
			$sender->sendMessage(TextFormat::RED . "Usage: " . $this->getUsage());
			return true;
		}

		$world = $sender->getWorld();
		if($world->getProvider()->getWorldData()->getGenerator() !== "vanilla_overworld"){
			$sender->sendMessage(TextFormat::RED . "This world was not generated by vanilla_overworld");
			return true;
		}

		$name = strtolower(str_replace(["minecraft:", " "], ["", "_"], $args[1]));

		if($mode === "structure"){
			return $this->locateStructure($sender, $world, $name, $args);
		}
		$biomeId = VanillaBiomeSelector::GENERATED_BIOMES[$name] ?? null;
		if($biomeId === null){
			$sender->sendMessage(TextFormat::RED . "The overworld generator never produces " . $name);
			$sender->sendMessage(TextFormat::GRAY . "Available: " . implode(", ", self::getBiomeNames()));
			return true;
		}

		$radius = isset($args[2]) && is_numeric($args[2]) ? (int) $args[2] >> Chunk::COORD_BIT_SIZE : self::DEFAULT_RADIUS_CHUNKS;
		$radius = max(1, min(self::MAX_RADIUS_CHUNKS, $radius));

		$found = $this->search($world, $sender->getPosition()->getFloorX(), $sender->getPosition()->getFloorZ(), $biomeId, $radius);
		if($found === null){
			$sender->sendMessage(TextFormat::RED . "Could not find " . $name . " within " . ($radius << Chunk::COORD_BIT_SIZE) . " blocks");
			return true;
		}

		[$x, $z, $height] = $found;
		$distance = (int) round(sqrt(($x - $sender->getPosition()->x) ** 2 + ($z - $sender->getPosition()->z) ** 2));

		$sender->sendMessage(TextFormat::GREEN . "The nearest " . $name . " is at " .
			TextFormat::WHITE . $x . ", " . $height . ", " . $z .
			TextFormat::GREEN . " (" . $distance . " blocks away)");

		if(isset($args[3]) && strtolower($args[3]) === "true"){
			$sender->teleport(new Vector3($x + 0.5, $height + 1, $z + 0.5));
		}

		return true;
	}

	/**
	 * Walks a square spiral outwards, one chunk per step, and samples the biome at the middle of each.
	 *
	 * @return array|null
	 * @phpstan-return array{int, int, int}|null
	 */
	private function search(World $world, int $centerX, int $centerZ, int $biomeId, int $radiusChunks) : ?array{
		$router = new NoiseRouter(new Random($world->getSeed()));
		$selector = new VanillaBiomeSelector($router);

		$x = 0;
		$z = 0;
		$dx = 0;
		$dz = -1;

		$steps = min(self::MAX_SAMPLES, (($radiusChunks * 2) + 1) ** 2);
		for($step = 0; $step < $steps; $step++){
			$checkX = $centerX + ($x << Chunk::COORD_BIT_SIZE);
			$checkZ = $centerZ + ($z << Chunk::COORD_BIT_SIZE);

			if($selector->pickBiome($checkX, $checkZ) === $biomeId){
				return [$checkX, $checkZ, max($router->getTerrainHeight($checkX, $checkZ), VanillaOverworld::SEA_LEVEL)];
			}

			if($x === $z || ($x < 0 && $x === -$z) || ($x > 0 && $x === 1 - $z)){
				$previousDx = $dx;
				$dx = -$dz;
				$dz = $previousDx;
			}

			$x += $dx;
			$z += $dz;
		}

		return null;
	}

	/**
	 * @param string[] $args
	 */
	private function locateStructure(Player $sender, World $world, string $name, array $args) : bool{
		$structure = StructureRegistry::get($name);
		if($structure === null){
			$sender->sendMessage(TextFormat::RED . "Unknown structure " . $name);
			$sender->sendMessage(TextFormat::GRAY . "Available: " . implode(", ", StructureRegistry::getNames()));
			return true;
		}

		$placement = $structure->getPlacement();
		if($placement->getMaxDistance() <= 1){
			$sender->sendMessage(TextFormat::RED . ucfirst(str_replace("_", " ", $name)) . " is scattered at random rather than placed on a grid, so it cannot be located");
			return true;
		}

		$radius = isset($args[2]) && is_numeric($args[2]) ? (int) $args[2] >> Chunk::COORD_BIT_SIZE : self::DEFAULT_RADIUS_CHUNKS;
		$radius = max(1, min(self::MAX_RADIUS_CHUNKS, $radius));

		$found = $this->searchStructure($world, $sender->getPosition()->getFloorX() >> Chunk::COORD_BIT_SIZE, $sender->getPosition()->getFloorZ() >> Chunk::COORD_BIT_SIZE, $structure, $radius);
		if($found === null){
			$sender->sendMessage(TextFormat::RED . "Could not find " . $name . " within " . ($radius << Chunk::COORD_BIT_SIZE) . " blocks");
			return true;
		}

		[$chunkX, $chunkZ] = $found;
		$x = ($chunkX << Chunk::COORD_BIT_SIZE) + 8;
		$z = ($chunkZ << Chunk::COORD_BIT_SIZE) + 8;

		$router = new NoiseRouter(new Random($world->getSeed()));
		$y = max($router->getTerrainHeight($x, $z), VanillaOverworld::SEA_LEVEL);
		$distance = (int) round(sqrt(($x - $sender->getPosition()->x) ** 2 + ($z - $sender->getPosition()->z) ** 2));

		$sender->sendMessage(TextFormat::GREEN . "The nearest " . $name . " is at " .
			TextFormat::WHITE . $x . ", " . $y . ", " . $z .
			TextFormat::GREEN . " (" . $distance . " blocks away)");

		if(isset($args[3]) && strtolower($args[3]) === "true"){
			$sender->teleport(new Vector3($x + 0.5, $y + 1, $z + 0.5));
		}

		return true;
	}

	/**
	 * Structures sit on a grid of regions, so the search walks the regions around the player rather than every
	 * chunk, and asks each one where its candidate chunk fell.
	 *
	 * @return int[]|null
	 * @phpstan-return array{int, int}|null
	 */
	private function searchStructure(World $world, int $centerChunkX, int $centerChunkZ, Structure $structure, int $radiusChunks) : ?array{
		$placement = $structure->getPlacement();
		$spacing = $placement->getMaxDistance();
		$random = new Random($world->getSeed());
		$router = new NoiseRouter(new Random($world->getSeed()));
		$selector = new VanillaBiomeSelector($router);

		$regionRadius = (int) ceil($radiusChunks / $spacing);
		$best = null;
		$bestDistance = null;

		for($regionX = StructurePlacement::regionCoord($centerChunkX, $spacing) - $regionRadius; $regionX <= StructurePlacement::regionCoord($centerChunkX, $spacing) + $regionRadius; ++$regionX){
			for($regionZ = StructurePlacement::regionCoord($centerChunkZ, $spacing) - $regionRadius; $regionZ <= StructurePlacement::regionCoord($centerChunkZ, $spacing) + $regionRadius; ++$regionZ){
				[$chunkX, $chunkZ] = $placement->getCandidateChunk($world->getSeed(), $random, $regionX, $regionZ);

				$sampleX = ($chunkX << Chunk::COORD_BIT_SIZE) + 7;
				$sampleZ = ($chunkZ << Chunk::COORD_BIT_SIZE) + 7;
				if(!$placement->isBiomeValid($selector->pickBiome($sampleX, $sampleZ))){
					continue;
				}

				$distance = (($chunkX - $centerChunkX) ** 2) + (($chunkZ - $centerChunkZ) ** 2);
				if($bestDistance === null || $distance < $bestDistance){
					$bestDistance = $distance;
					$best = [$chunkX, $chunkZ];
				}
			}
		}

		return $best;
	}

	/**
	 * @return string[]
	 */
	public static function getBiomeNames() : array{
		$names = array_keys(VanillaBiomeSelector::GENERATED_BIOMES);
		sort($names);

		return $names;
	}
}
